#compdef ogp

# OGP zsh completion script
# Auto-generated by ogp completion install

_ogp() {
  local -a frameworks peers
  local curcontext="$curcontext" state line
  typeset -A opt_args

  # Get frameworks for --for flag
  frameworks=(${(f)"$(ogp config list --quiet 2>/dev/null)"} all)

  _arguments -C \
    '(- *)'{-h,--help}'[Show help]' \
    '(- *)'{-v,--version}'[Show version]' \
    '--for[Select framework]:framework:($frameworks)' \
    '1: :->command' \
    '*::arg:->args'

  case "$state" in
    command)
      _arguments '1:command:((
        setup\:"Initialize OGP configuration"
        start\:"Start OGP daemon"
        stop\:"Stop OGP daemon"
        status\:"Show daemon status"
        federation\:"Manage federation"
        agent-comms\:"Configure agent-to-agent messaging"
        config\:"Manage configuration"
        expose\:"Expose daemon via tunnel"
        expose-stop\:"Stop background tunnel"
        shutdown\:"Stop daemon and tunnel"
        install\:"Install LaunchAgent (macOS)"
        uninstall\:"Uninstall LaunchAgent (macOS)"
        intent\:"Manage custom intents"
        project\:"Manage project contexts"
        completion\:"Install completion scripts"
      ))'
      ;;
    args)
      case ${words[1]} in
        federation)
          _ogp_federation
          ;;
        agent-comms)
          _ogp_agent_comms
          ;;
        config)
          _ogp_config
          ;;
        intent)
          _ogp_intent
          ;;
        project)
          _ogp_project
          ;;
        completion)
          _ogp_completion
          ;;
        expose)
          _ogp_expose
          ;;
      esac
      ;;
  esac
}

_ogp_federation() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments '1:subcommand:((
    list\:"List all peers"
    status\:"Show federation status and alias mappings"
    request\:"Send federation request to a peer"
    connect\:"Connect to peer by public key via rendezvous"
    invite\:"Generate invite token to share with peer"
    accept\:"Accept peer invite token and connect"
    approve\:"Approve pending federation request"
    reject\:"Reject pending federation request"
    remove\:"Remove peer from federation list"
    alias\:"Set user-friendly alias for peer"
    tag\:"Add tags to a peer (local categorization)"
    untag\:"Remove tags from a peer"
    ping\:"Ping peer gateway to test connectivity"
    send\:"Send message to federated peer"
    scopes\:"Show scope grants for peer"
    grant\:"Update scope grants for approved peer"
    agent\:"Send agent-comms message to peer"
  ))' \
  '*::arg:->args'

  case "$state" in
    args)
      case ${words[1]} in
        list)
          _arguments \
            '(-s --status)'{-s,--status}'[Filter by status]:status:(pending approved rejected removed)'
          ;;
        request)
          _arguments \
            '1:peer-url:' \
            '2:peer-id::' \
            '(-a --alias)'{-a,--alias}'[User-friendly alias]:alias:' \
            '--petname[Deprecated - use --alias]:petname:'
          ;;
        connect|accept)
          _arguments \
            '1:identifier:' \
            '(-a --alias)'{-a,--alias}'[User-friendly alias]:alias:' \
            '--petname[Deprecated - use --alias]:petname:'
          ;;
        approve)
          _arguments \
            '1:peer-id:' \
            '--intents[Comma-separated intents to grant]:intents:' \
            '--rate[Rate limit as requests/seconds]:rate:' \
            '--topics[Comma-separated topics for agent-comms]:topics:'
          ;;
        reject|remove|scopes|alias)
          _arguments '1:peer-id:'
          ;;
        send)
          _arguments \
            '1:peer-id:' \
            '2:intent:' \
            '3:payload:'
          ;;
        grant)
          _arguments \
            '1:peer-id:' \
            '--intents[Comma-separated intents to grant]:intents:' \
            '--rate[Rate limit as requests/seconds]:rate:' \
            '--topics[Comma-separated topics for agent-comms]:topics:'
          ;;
        agent)
          _arguments \
            '1:peer-id:' \
            '2:topic:' \
            '3:message:' \
            '(-p --priority)'{-p,--priority}'[Priority level]:priority:(low normal high)' \
            '(-c --conversation)'{-c,--conversation}'[Conversation ID]:conversation-id:' \
            '(-w --wait)'{-w,--wait}'[Wait for reply]' \
            '(-t --timeout)'{-t,--timeout}'[Reply timeout in milliseconds]:timeout:'
          ;;
      esac
      ;;
  esac
}

_ogp_agent_comms() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments '1:subcommand:((
    policies\:"Show response policies"
    configure\:"Configure response policies"
    add-topic\:"Add topic to peer response policy"
    set-topic\:"Set topic policy for peer"
    set-default\:"Set per-peer default level"
    remove-topic\:"Remove topic from peer policy"
    reset\:"Reset peer policy to global defaults"
    activity\:"Show agent-comms activity log"
    default\:"Set default response level for unknown topics"
    logging\:"Enable or disable activity logging"
  ))' \
  '*::arg:->args'

  case "$state" in
    args)
      case ${words[1]} in
        policies|activity)
          _arguments '1:peer-id::'
          ;;
        configure)
          _arguments \
            '1:peer-ids::' \
            '--global[Configure global default policies]' \
            '--topics[Comma-separated topics]:topics:' \
            '--level[Response level]:level:(full summary escalate deny off)' \
            '--notes[Policy notes]:notes:'
          ;;
        add-topic)
          _arguments \
            '1:peer-id:' \
            '2:topic:' \
            '--level[Response level]:level:(full summary escalate deny off)' \
            '--notes[Topic notes]:notes:'
          ;;
        set-topic)
          _arguments \
            '1:peer-id:' \
            '2:topic:' \
            '3:level:(full summary escalate deny off)' \
            '--notes[Topic notes]:notes:'
          ;;
        set-default)
          _arguments \
            '1:peer-id:' \
            '2:level:(full summary escalate deny off)'
          ;;
        remove-topic|reset)
          _arguments '1:peer-id:' '2:topic::'
          ;;
        default)
          _arguments '1:level:(full summary escalate deny off)'
          ;;
        logging)
          _arguments '1:state:(on off true false enable disable)'
          ;;
      esac
      ;;
  esac
}

_ogp_config() {
  local curcontext="$curcontext" state line
  typeset -A opt_args
  local -a frameworks
  frameworks=(${(f)"$(ogp config list --quiet 2>/dev/null)"})

  _arguments '1:subcommand:((
    show\:"Show all configured frameworks and default"
    set-default\:"Set default framework"
    list\:"List all frameworks"
    enable\:"Enable a framework"
    disable\:"Disable a framework"
    frameworks\:"Show all detected frameworks"
    health-check\:"Manage health check configuration"
    show-identity\:"Show current identity configuration"
    set-identity\:"Update identity information"
    set-tags\:"Set tags (replaces existing)"
    add-tag\:"Add a tag"
    remove-tag\:"Remove a tag"
  ))' \
  '*::arg:->args'

  case "$state" in
    args)
      case ${words[1]} in
        set-default|enable|disable)
          _arguments "1:framework:($frameworks)"
          ;;
        list)
          _arguments '(-q --quiet)'{-q,--quiet}'[Output framework IDs only]'
          ;;
        health-check)
          _ogp_config_health_check
          ;;
        set-identity)
          _arguments \
            '--human-name[Human operator name]:name:' \
            '--agent-name[Agent name]:name:' \
            '--organization[Organization name]:org:'
          ;;
      esac
      ;;
  esac
}

_ogp_config_health_check() {
  _arguments '1:subcommand:((
    show\:"Show current health check configuration"
    interval\:"Set health check interval in milliseconds"
    timeout\:"Set health check timeout in milliseconds"
    max-failures\:"Set max consecutive failures before unhealthy"
  ))' \
  '*::arg:->args'
}

_ogp_intent() {
  _arguments '1:subcommand:((
    register\:"Register new intent handler"
    list\:"List all registered intents"
    remove\:"Remove registered intent"
  ))' \
  '*::arg:->args'

  case "$state" in
    args)
      case ${words[1]} in
        register)
          _arguments \
            '1:name:' \
            '--script[Path to handler script]:script:_files' \
            '--description[Intent description]:description:'
          ;;
        remove)
          _arguments '1:name:'
          ;;
      esac
      ;;
  esac
}

_ogp_project() {
  _arguments '1:subcommand:((
    create\:"Create new project locally"
    join\:"Join existing project"
    list\:"List all local projects"
    remove\:"Remove local project"
    contribute\:"Add contribution to project"
    query\:"Query project contributions"
    status\:"Show project status overview"
    request-join\:"Request to join project from peer"
    send-contribution\:"Send contribution to peer project"
    query-peer\:"Query peer project contributions"
    status-peer\:"Request project status from peer"
    delete\:"Delete local project and all contributions"
  ))' \
  '*::arg:->args'

  case "$state" in
    args)
      case ${words[1]} in
        create)
          _arguments \
            '1:project-id:' \
            '2:project-name:' \
            '--description[Project description]:description:'
          ;;
        join)
          _arguments \
            '1:project-id:' \
            '2:project-name::' \
            '--create[Create project if not exists]' \
            '--description[Project description]:description:'
          ;;
        remove|status|delete)
          _arguments \
            '1:project-id:' \
            '--force[Skip confirmation prompt]'
          ;;
        contribute)
          _arguments \
            '1:project-id:' \
            '2:type:' \
            '3:summary:' \
            '--metadata[Additional structured data as JSON]:metadata:' \
            '--local-only[Skip auto-push to federated peers]'
          ;;
        query)
          _arguments \
            '1:project-id:' \
            '--type[Filter by entry type]:type:' \
            '--topic[Filter by entry type (alias)]:topic:' \
            '--author[Filter by author]:author:' \
            '--search[Search by text content]:search:' \
            '--limit[Maximum results]:limit:'
          ;;
        request-join)
          _arguments \
            '1:peer-id:' \
            '2:project-id:' \
            '3:project-name:' \
            '--description[Project description]:description:'
          ;;
        send-contribution)
          _arguments \
            '1:peer-id:' \
            '2:project-id:' \
            '3:type:' \
            '4:summary:' \
            '--metadata[Additional structured data as JSON]:metadata:'
          ;;
        query-peer)
          _arguments \
            '1:peer-id:' \
            '2:project-id:' \
            '--type[Filter by entry type]:type:' \
            '--topic[Filter by entry type (alias)]:topic:' \
            '--author[Filter by author]:author:' \
            '--limit[Maximum results]:limit:' \
            '--timeout[Response timeout in milliseconds]:timeout:'
          ;;
        status-peer)
          _arguments \
            '1:peer-id:' \
            '2:project-id:'
          ;;
      esac
      ;;
  esac
}

_ogp_completion() {
  _arguments '1:subcommand:((
    install\:"Install completion scripts for current shell"
  ))'
}

_ogp_expose() {
  _arguments \
    '(-m --method)'{-m,--method}'[Tunnel method]:method:(cloudflared ngrok)' \
    '(-b --background)'{-b,--background}'[Run in background]'
}

_ogp
