#compdef ogp

# OGP zsh completion script
# Auto-generated by ogp completion install

_ogp_command_word() {
  local i=2

  while (( i <= $#words )); do
    case "${words[i]}" in
      --for)
        (( i += 2 ))
        continue
        ;;
      --for=*)
        (( i += 1 ))
        continue
        ;;
      -h|--help|-v|--version)
        (( i += 1 ))
        continue
        ;;
      -*)
        (( i += 1 ))
        continue
        ;;
      *)
        print -r -- "${words[i]}"
        return 0
        ;;
    esac
  done

  return 1
}

_ogp_subcommand_word() {
  local parent="$1"
  local seen_parent=0
  local i=2

  while (( i <= $#words )); do
    case "${words[i]}" in
      --for)
        (( i += 2 ))
        continue
        ;;
      --for=*)
        (( i += 1 ))
        continue
        ;;
      -*)
        (( i += 1 ))
        continue
        ;;
    esac

    if (( seen_parent == 0 )); then
      if [[ "${words[i]}" == "$parent" ]]; then
        seen_parent=1
      fi
      (( i += 1 ))
      continue
    fi

    print -r -- "${words[i]}"
    return 0
  done

  return 1
}

_ogp() {
  local -a frameworks
  local curcontext="$curcontext" state line
  typeset -A opt_args

  frameworks=(${(f)"$(ogp config list --quiet 2>/dev/null)"} all)

  _arguments -C \
    '(- *)'{-h,--help}'[Show help]' \
    '(- *)'{-v,--version}'[Show version]' \
    '--for[Select framework]:framework:($frameworks)' \
    '1: :->command' \
    '*::arg:->args'

  case "$state" in
    command)
      _arguments '1:command:((
        setup\:"Initialize OGP configuration"
        start\:"Start OGP daemon"
        stop\:"Stop OGP daemon"
        status\:"Show daemon status"
        whoami\:"Show current identity and configuration"
        federation\:"Manage federation"
        agent-comms\:"Configure agent-to-agent messaging"
        config\:"Manage configuration"
        expose\:"Expose daemon via tunnel"
        expose-stop\:"Stop background tunnel"
        shutdown\:"Stop daemon and tunnel"
        install\:"Install LaunchAgent (macOS)"
        uninstall\:"Uninstall LaunchAgent (macOS)"
        intent\:"Manage custom intents"
        project\:"Manage project contexts"
        completion\:"Install completion scripts"
      ))'
      ;;
    args)
      case "$(_ogp_command_word)" in
        federation)
          _ogp_federation
          ;;
        agent-comms)
          _ogp_agent_comms
          ;;
        config)
          _ogp_config
          ;;
        intent)
          _ogp_intent
          ;;
        project)
          _ogp_project
          ;;
        completion)
          _ogp_completion
          ;;
        expose)
          _ogp_expose
          ;;
      esac
      ;;
  esac
}

_ogp_federation() {
  local curcontext="$curcontext" state line
  local subcmd="$(_ogp_subcommand_word federation)"
  typeset -A opt_args

  _arguments \
    '1:subcommand:((
      list\:"List all peers"
      status\:"Show federation status and alias mappings"
      request\:"Send federation request to a peer"
      connect\:"Connect to peer by public key via rendezvous"
      invite\:"Generate invite token to share with peer"
      accept\:"Accept peer invite token and connect"
      approve\:"Approve pending federation request"
      reject\:"Reject pending federation request"
      remove\:"Remove peer from federation list"
      alias\:"Set user-friendly alias for peer"
      tag\:"Add tags to a peer (local categorization)"
      untag\:"Remove tags from a peer"
      update-identity\:"Send updated identity information to approved peer"
      ping\:"Ping peer gateway to test connectivity"
      send\:"Send message to federated peer"
      scopes\:"Show scope grants for peer"
      grant\:"Update scope grants for approved peer"
      agent\:"Send agent-comms message to peer"
    ))' \
    '*::arg:->args'

  case "$state" in
    args)
      case "$subcmd" in
        list)
          _arguments \
            '(-s --status)'{-s,--status}'[Filter by status]:status:(pending approved rejected removed)' \
            '(-t --tag)'{-t,--tag}'[Filter by tag]:tag:'
          ;;
        request)
          _arguments \
            '1:peer-url:' \
            '2:alias::' \
            '(-a --alias)'{-a,--alias}'[User-friendly alias]:alias:' \
            '--petname[Deprecated - use --alias]:petname:'
          ;;
        connect|accept)
          _arguments \
            '1:identifier:' \
            '(-a --alias)'{-a,--alias}'[User-friendly alias]:alias:' \
            '--petname[Deprecated - use --alias]:petname:'
          ;;
        approve|grant)
          _arguments \
            '1:peer-id:' \
            '--intents[Comma-separated intents to grant]:intents:' \
            '--rate[Rate limit as requests/windowSeconds]:rate:' \
            '--topics[Comma-separated topics for agent-comms]:topics:'
          ;;
        reject|remove|scopes|update-identity)
          _arguments '1:peer-id:'
          ;;
        alias)
          _arguments \
            '1:peer-id:' \
            '2:alias:'
          ;;
        tag|untag)
          _arguments \
            '1:peer-id:' \
            '*:tag:'
          ;;
        ping)
          _arguments '1:peer-url:'
          ;;
        send)
          _arguments \
            '1:peer-id:' \
            '2:intent:' \
            '3:payload:' \
            '--to-agent[Target a specific persona on the peer]:persona:'
          ;;
        agent)
          _arguments \
            '1:peer-id:' \
            '2:topic:' \
            '3:message:' \
            '(-p --priority)'{-p,--priority}'[Priority level]:priority:(low normal high)' \
            '(-c --conversation)'{-c,--conversation}'[Conversation ID]:conversation-id:' \
            '(-w --wait)'{-w,--wait}'[Wait for reply]' \
            '(-t --timeout)'{-t,--timeout}'[Reply timeout in milliseconds]:timeout:' \
            '--to-agent[Target a specific persona on the peer]:persona:'
          ;;
      esac
      ;;
  esac
}

_ogp_agent_comms() {
  local curcontext="$curcontext" state line
  local subcmd="$(_ogp_subcommand_word agent-comms)"
  typeset -A opt_args

  _arguments \
    '1:subcommand:((
      policies\:"Show response policies"
      configure\:"Configure response policies"
      add-topic\:"Add topic to peer response policy"
      set-topic\:"Set topic policy for peer"
      set-default\:"Set per-peer default level"
      remove-topic\:"Remove topic from peer policy"
      reset\:"Reset peer policy to global defaults"
      activity\:"Show agent-comms activity log"
      default\:"Set default response level for unknown topics"
      logging\:"Enable or disable activity logging"
    ))' \
    '*::arg:->args'

  case "$state" in
    args)
      case "$subcmd" in
        policies|activity)
          _arguments '1:peer-id::'
          ;;
        configure)
          _arguments \
            '1:peer-ids::' \
            '--global[Configure global default policies]' \
            '--topics[Comma-separated topics]:topics:' \
            '--level[Response level]:level:(full summary escalate deny off)' \
            '--notes[Policy notes]:notes:'
          ;;
        add-topic)
          _arguments \
            '1:peer-id:' \
            '2:topic:' \
            '--level[Response level]:level:(full summary escalate deny off)' \
            '--notes[Topic notes]:notes:'
          ;;
        set-topic)
          _arguments \
            '1:peer-id:' \
            '2:topic:' \
            '3:level:(full summary escalate deny off)' \
            '--notes[Topic notes]:notes:'
          ;;
        set-default)
          _arguments \
            '1:peer-id:' \
            '2:level:(full summary escalate deny off)'
          ;;
        remove-topic)
          _arguments \
            '1:peer-id:' \
            '2:topic:'
          ;;
        reset)
          _arguments '1:peer-id:'
          ;;
        default)
          _arguments '1:level:(full summary escalate deny off)'
          ;;
        logging)
          _arguments '1:state:(on off true false enable disable)'
          ;;
      esac
      ;;
  esac
}

_ogp_config() {
  local curcontext="$curcontext" state line
  local -a frameworks
  local subcmd="$(_ogp_subcommand_word config)"
  typeset -A opt_args

  frameworks=(${(f)"$(ogp config list --quiet 2>/dev/null)"})

  _arguments \
    '1:subcommand:((
      show\:"Show all configured frameworks and default"
      set-default\:"Set default framework"
      list\:"List all frameworks"
      enable\:"Enable a framework"
      disable\:"Disable a framework"
      frameworks\:"Show all detected frameworks"
      health-check\:"Manage health check configuration"
      show-identity\:"Show current identity configuration"
      set-identity\:"Update identity information"
      set-tags\:"Set tags (replaces existing)"
      add-tag\:"Add a tag"
      remove-tag\:"Remove a tag"
    ))' \
    '*::arg:->args'

  case "$state" in
    args)
      case "$subcmd" in
        set-default|enable|disable)
          _arguments "1:framework:($frameworks)"
          ;;
        list)
          _arguments '(-q --quiet)'{-q,--quiet}'[Output framework IDs only]'
          ;;
        health-check)
          _ogp_config_health_check
          ;;
        set-identity)
          _arguments \
            '--human-name[Human operator name]:name:' \
            '--agent-name[Agent name]:name:' \
            '--organization[Organization name]:org:'
          ;;
        set-tags)
          _arguments '*:tag:'
          ;;
        add-tag|remove-tag)
          _arguments '1:tag:'
          ;;
      esac
      ;;
  esac
}

_ogp_config_health_check() {
  local curcontext="$curcontext" state line
  local subcmd="$(_ogp_subcommand_word health-check)"
  typeset -A opt_args

  _arguments \
    '1:subcommand:((
      show\:"Show current health check configuration"
      interval\:"Set health check interval in milliseconds"
      timeout\:"Set health check timeout in milliseconds"
      max-failures\:"Set max consecutive failures before unhealthy"
    ))' \
    '*::arg:->args'

  case "$state" in
    args)
      case "$subcmd" in
        interval|timeout|max-failures)
          _arguments '1:value:'
          ;;
      esac
      ;;
  esac
}

_ogp_intent() {
  local curcontext="$curcontext" state line
  local subcmd="$(_ogp_subcommand_word intent)"
  typeset -A opt_args

  _arguments \
    '1:subcommand:((
      register\:"Register new intent handler"
      list\:"List all registered intents"
      remove\:"Remove registered intent"
    ))' \
    '*::arg:->args'

  case "$state" in
    args)
      case "$subcmd" in
        register)
          _arguments \
            '1:name:' \
            '--script[Path to handler script]:script:_files' \
            '--description[Intent description]:description:'
          ;;
        remove)
          _arguments '1:name:'
          ;;
      esac
      ;;
  esac
}

_ogp_project() {
  local curcontext="$curcontext" state line
  local subcmd="$(_ogp_subcommand_word project)"
  typeset -A opt_args

  _arguments \
    '1:subcommand:((
      create\:"Create new project locally"
      join\:"Join existing project"
      list\:"List all local projects"
      remove\:"Remove local project"
      contribute\:"Add contribution to project"
      query\:"Query project contributions"
      status\:"Show project status overview"
      request-join\:"Request to join project from peer"
      send-contribution\:"Send contribution to peer project"
      query-peer\:"Query peer project contributions"
      status-peer\:"Request project status from peer"
      delete\:"Delete local project and all contributions"
    ))' \
    '*::arg:->args'

  case "$state" in
    args)
      case "$subcmd" in
        create)
          _arguments \
            '1:project-id:' \
            '2:project-name:' \
            '--description[Project description]:description:'
          ;;
        join)
          _arguments \
            '1:project-id:' \
            '2:project-name::' \
            '--create[Create project if not exists]' \
            '--description[Project description]:description:'
          ;;
        remove|status|delete)
          _arguments \
            '1:project-id:' \
            '--force[Skip confirmation prompt]'
          ;;
        contribute)
          _arguments \
            '1:project-id:' \
            '2:type:' \
            '3:summary:' \
            '--metadata[Additional structured data as JSON]:metadata:' \
            '--local-only[Skip auto-push to federated peers]' \
            '--to-agent[Target a persona on each peer auto-push target]:persona:'
          ;;
        query)
          _arguments \
            '1:project-id:' \
            '--type[Filter by entry type]:type:' \
            '--topic[Filter by entry type (alias)]:topic:' \
            '--author[Filter by author]:author:' \
            '--search[Search by text content]:search:' \
            '--limit[Maximum results]:limit:'
          ;;
        request-join)
          _arguments \
            '1:peer-id:' \
            '2:project-id:' \
            '3:project-name:' \
            '--description[Project description]:description:'
          ;;
        send-contribution)
          _arguments \
            '1:peer-id:' \
            '2:project-id:' \
            '3:type:' \
            '4:summary:' \
            '--metadata[Additional structured data as JSON]:metadata:' \
            '--to-agent[Target a specific persona on the peer]:persona:'
          ;;
        query-peer)
          _arguments \
            '1:peer-id:' \
            '2:project-id:' \
            '--type[Filter by entry type]:type:' \
            '--topic[Filter by entry type (alias)]:topic:' \
            '--author[Filter by author]:author:' \
            '--limit[Maximum results]:limit:' \
            '--timeout[Response timeout in milliseconds]:timeout:'
          ;;
        status-peer)
          _arguments \
            '1:peer-id:' \
            '2:project-id:'
          ;;
      esac
      ;;
  esac
}

_ogp_completion() {
  _arguments '1:subcommand:((
    install\:"Install completion scripts for current shell"
  ))'
}

_ogp_expose() {
  _arguments \
    '(-m --method)'{-m,--method}'[Tunnel method]:method:(cloudflared ngrok)' \
    '(-b --background)'{-b,--background}'[Run in background]'
}

_ogp
