#!/usr/bin/env bash

# OGP bash completion script
# Auto-generated by ogp completion install

_ogp_completion() {
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  # Get the first command (after ogp)
  local cmd=""
  if [ $COMP_CWORD -ge 1 ]; then
    cmd="${COMP_WORDS[1]}"
  fi

  # Get the second command (for subcommands)
  local subcmd=""
  if [ $COMP_CWORD -ge 2 ]; then
    subcmd="${COMP_WORDS[2]}"
  fi

  # --for flag completion (can appear anywhere)
  if [ "$prev" = "--for" ]; then
    local frameworks=$(ogp config list --quiet 2>/dev/null || echo "")
    COMPREPLY=( $(compgen -W "${frameworks} all" -- ${cur}) )
    return 0
  fi

  # Top-level commands
  if [ $COMP_CWORD -eq 1 ]; then
    opts="setup start stop status whoami federation agent-comms config expose expose-stop shutdown install uninstall intent project completion"
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
  fi

  # federation subcommands
  if [ "$cmd" = "federation" ]; then
    if [ $COMP_CWORD -eq 2 ]; then
      opts="list status request connect invite accept approve reject remove alias tag untag update-identity ping send scopes grant agent"
      COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
      return 0
    fi

    # --to-agent (B0032 v0.7.0): targets a specific persona on the peer.
    # Available on: federation send, federation agent
    if [[ "$subcmd" == "send" || "$subcmd" == "agent" ]]; then
      if [[ "$cur" == --* ]]; then
        opts="--to-agent"
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
      fi
    fi

    # For federation commands that need peer-id, we could add dynamic peer completion here
    # TODO: ogp federation list --quiet to get peer IDs/aliases
    return 0
  fi

  # agent-comms subcommands
  if [ "$cmd" = "agent-comms" ]; then
    if [ $COMP_CWORD -eq 2 ]; then
      opts="policies configure add-topic set-topic set-default remove-topic reset activity default logging"
      COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
      return 0
    fi
    return 0
  fi

  # config subcommands
  if [ "$cmd" = "config" ]; then
    if [ $COMP_CWORD -eq 2 ]; then
      opts="show set-default list enable disable frameworks health-check show-identity set-identity set-tags add-tag remove-tag"
      COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
      return 0
    fi

    # health-check subcommands
    if [ "$subcmd" = "health-check" ]; then
      if [ $COMP_CWORD -eq 3 ]; then
        opts="show interval timeout max-failures"
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
      fi
    fi

    # set-identity flags
    if [ "$subcmd" = "set-identity" ]; then
      opts="--human-name --agent-name --organization"
      COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
      return 0
    fi

    # For config commands that need framework ID
    if [[ "$subcmd" == "set-default" || "$subcmd" == "enable" || "$subcmd" == "disable" ]]; then
      if [ $COMP_CWORD -eq 3 ]; then
        local frameworks=$(ogp config list --quiet 2>/dev/null || echo "")
        COMPREPLY=( $(compgen -W "${frameworks}" -- ${cur}) )
        return 0
      fi
    fi
    return 0
  fi

  # intent subcommands
  if [ "$cmd" = "intent" ]; then
    if [ $COMP_CWORD -eq 2 ]; then
      opts="register list remove"
      COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
      return 0
    fi
    return 0
  fi

  # project subcommands
  if [ "$cmd" = "project" ]; then
    if [ $COMP_CWORD -eq 2 ]; then
      opts="create join list remove contribute query status request-join send-contribution query-peer status-peer delete"
      COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
      return 0
    fi

    # --to-agent (B0032 v0.7.0): targets a specific persona on the peer.
    # Available on: project contribute (auto-push), project send-contribution
    if [[ "$subcmd" == "contribute" || "$subcmd" == "send-contribution" ]]; then
      if [[ "$cur" == --* ]]; then
        if [ "$subcmd" = "contribute" ]; then
          opts="--metadata --local-only --to-agent"
        else
          opts="--metadata --to-agent"
        fi
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
      fi
    fi
    return 0
  fi

  # completion subcommands
  if [ "$cmd" = "completion" ]; then
    if [ $COMP_CWORD -eq 2 ]; then
      opts="install"
      COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
      return 0
    fi
    return 0
  fi

  # expose subcommands
  if [ "$cmd" = "expose" ]; then
    if [ "$prev" = "-m" ] || [ "$prev" = "--method" ]; then
      opts="cloudflared ngrok"
      COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
      return 0
    fi
    return 0
  fi

  return 0
}

complete -F _ogp_completion ogp
